velux:
  address: "192.168.0.112"
  password: "a3gUeKQ2eG"

knx:
  address: "192.168.0.111"
  port: 3671

devices:
  - name: "Büro 1 links"
    velux_name: "01_links"
    knx:
      up_down_long: "1/1/0"
      up_down_short: "1/1/1"
      position_height: "1/1/2"
      position_height_state: "1/1/6"
      position_slat: "1/1/3"
      position_slat_state: "1/1/7"
  - name: "Büro 1 rechts" 
    velux_name: "01_rechts"
    knx:
      up_down_long: "1/1/10"
      up_down_short: "1/1/11"
      position_height: "1/1/12"
      position_height_state: "1/1/16"
      position_slat: "1/1/13"
      position_slat_state: "1/1/17"
  - name: "Büro 2 links"
    velux_name: "02_links"
    knx:
      up_down_long: "1/1/20"
      up_down_short: "1/1/21"
      position_height: "1/1/22"
      position_height_state: "1/1/26"
      position_slat: "1/1/23"
      position_slat_state: "1/1/27"
  - name: "Büro 2 rechts"
    velux_name: "02_rechts" 
    knx:
      up_down_long: "1/1/30"
      up_down_short: "1/1/31"
      position_height: "1/1/32"
      position_height_state: "1/1/36"
      position_slat: "1/1/33"
      position_slat_state: "1/1/37"
  - name: "Büro 3 links"
    velux_name: "03_links"
    knx:
      up_down_long: "1/1/40"
      up_down_short: "1/1/41"
      position_height: "1/1/42"
      position_height_state: "1/1/46"
      position_slat: "1/1/43"
      position_slat_state: "1/1/47"
  - name: "Büro 3 rechts"
    velux_name: "03_rechts"
    knx:
      up_down_long: "1/1/50"
      up_down_short: "1/1/51"
      position_height: "1/1/52"
      position_height_state: "1/1/56"
      position_slat: "1/1/53"
      position_slat_state: "1/1/57"
  - name: "Büro 4 links"
    velux_name: "04_links"
    knx:
      up_down_long: "1/1/60"
      up_down_short: "1/1/61"
      position_height: "1/1/62"
      position_height_state: "1/1/66"
      position_slat: "1/1/63"
      position_slat_state: "1/1/67"
  - name: "Büro 4 rechts"
    velux_name: "04_rechts"
    knx:
      up_down_long: "1/1/70"
      up_down_short: "1/1/71"
      position_height: "1/1/72"
      position_height_state: "1/1/76"
      position_slat: "1/1/73"
      position_slat_state: "1/1/77"
  - name: "Büro 5 links"
    velux_name: "05_links"
    knx:
      up_down_long: "1/1/80"
      up_down_short: "1/1/81"
      position_height: "1/1/82"
      position_height_state: "1/1/86"
      position_slat: "1/1/83"
      position_slat_state: "1/1/87"
  - name: "Büro 5 rechts"
    velux_name: "05_rechts"
    knx:
      up_down_long: "1/1/90"
      up_down_short: "1/1/91"
      position_height: "1/1/92"
      position_height_state: "1/1/96"
      position_slat: "1/1/93"
      position_slat_state: "1/1/97"
  - name: "Büro 6 links"
    velux_name: "06_links"
    knx:
      up_down_long: "1/1/100"
      up_down_short: "1/1/101"
      position_height: "1/1/102"
      position_height_state: "1/1/106"
      position_slat: "1/1/103"
      position_slat_state: "1/1/107"
  - name: "Büro 6 rechts"
    velux_name: "06_rechts"
    knx:
      up_down_long: "1/1/110"
      up_down_short: "1/1/111"
      position_height: "1/1/112"
      position_height_state: "1/1/116"
      position_slat: "1/1/113"
      position_slat_state: "1/1/117"
  - name: "Büro 7 links"
    velux_name: "07_links"
    knx:
      up_down_long: "1/1/120"
      up_down_short: "1/1/121"
      position_height: "1/1/122"
      position_height_state: "1/1/126"
      position_slat: "1/1/123"
      position_slat_state: "1/1/127"
  - name: "Büro 7 rechts"
    velux_name: "07_rechts"
    knx:
      up_down_long: "1/1/130"
      up_down_short: "1/1/131"
      position_height: "1/1/132"
      position_height_state: "1/1/136"
      position_slat: "1/1/133"
      position_slat_state: "1/1/137"
  - name: "Archiv Links"
    velux_name: "archiv_links"
    knx:
      up_down_long: "1/1/140"
      up_down_short: "1/1/141"
      position_height: "1/1/142"
      position_height_state: "1/1/146"
      position_slat: "1/1/143"
      position_slat_state: "1/1/147" 
  - name: "Archiv rechts"
    velux_name: "archiv_rechts"
    knx:
      up_down_long: "1/1/150"
      up_down_short: "1/1/151"
      position_height: "1/1/152"
      position_height_state: "1/1/156"
      position_slat: "1/1/153"
      position_slat_state: "1/1/157" 
